"""Automated LaTeX compilation script generating an executive PDF methodology report."""
import subprocess
from pathlib import Path

LATEX_SOURCE = r"""
\documentclass[11pt,a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage[margin=0.75in]{geometry}
\usepackage{amsmath,amssymb,amsfonts}
\usepackage{tcolorbox}
\usepackage{tikz}
\usepackage{xcolor}
\usepackage{booktabs}

\definecolor{NavyBlue}{RGB}{31,73,125}
\definecolor{SoftBlue}{RGB}{220,230,241}

\tcbuselibrary{skins,breakable}
\newtcolorbox{execbox}[2][]{
    colback=SoftBlue!30,
    colframe=NavyBlue,
    fonttitle=\bfseries\sffamily,
    title=#2,#1,
    before skip=10pt, after skip=10pt
}

\title{\vspace{-1.5cm}\textbf{\color{NavyBlue} Valuation Studio: Institutional Methodology}}
\author{\textbf{An Vo} \\ M.Sc. Quantitative Economics, University of Bonn}
\date{\today\vspace{-0.5cm}}

\begin{document}
\maketitle

\begin{execbox}{Executive Briefing \& Architecture}
This document outlines the mathematical rigor and accounting principles underlying the
Valuation Studio engine. By replacing static spreadsheets with version-controlled Python
modules, this architecture guarantees balance sheet equilibrium, programmatically interpolates
Wall Street consensus estimates, and enables automated Margin of Safety screening.
\end{execbox}

\section*{1. Unlevered Free Cash Flow ($FCFF$)}
The core valuation engine computes cash generated by operations after accounting for
reinvestment in long-term assets and working capital:
\vspace{-0.2cm}
\begin{equation}
    FCFF = EBIT \cdot (1 - t) + D\&A - \Delta NWC - CapEx
\end{equation}

\section*{2. Dynamic Consensus Ingestion \& Growth Fade}
Unlike academic models that utilize flat growth rates, the engine anchors Year 1 and Year 2
to live Wall Street consensus estimates. For Years 3 through 5, the model applies a mathematical
decay (fade) towards the terminal GDP growth rate:
\vspace{-0.2cm}
\begin{equation}
    g_{t+1} = \max(g_{term}, g_t \cdot \delta)
\end{equation}
Where $\delta = 0.80$, representing a $20\%$ annual decay in hyper-growth velocity.

\section*{3. Dynamic Revolver Plug}
To maintain continuous balance sheet equilibrium ($Assets = Liabilities + Equity$), cash
surpluses and deficits adjust the capital structure dynamically:
\vspace{-0.2cm}
\begin{center}
\begin{tikzpicture}[node distance=3.2cm, auto, >=stealth, thick, scale=0.9, transform shape]
    \node [draw=NavyBlue, fill=SoftBlue!40, rectangle, rounded corners,
           minimum height=1cm, align=center] (fcfe) {Net Cash Flow\\ ($FCFE_{pre}$)};

    \node [draw=NavyBlue, fill=SoftBlue!40, rectangle, rounded corners,
           minimum height=1cm, align=center, right of=fcfe] (check) {Check Cash\\ vs. Minimum};

    \node [draw=green!50!black, fill=green!10, rectangle, rounded corners,
           minimum height=1cm, align=center, above right of=check] (surplus) {Surplus:\\ Pay Debt};

    \node [draw=red!50!black, fill=red!10, rectangle, rounded corners,
           minimum height=1cm, align=center, below right of=check] (def) {Deficit:\\ Draw Rev.};

    \draw[->] (fcfe) -- (check);
    \draw[->] (check) |- (surplus);
    \draw[->] (check) |- (def);
\end{tikzpicture}
\end{center}

\end{document}
"""


def compile_pdf() -> None:
    build_dir = Path("build/docs")
    build_dir.mkdir(parents=True, exist_ok=True)

    tex_path = build_dir / "methodology_report.tex"
    tex_path.write_text(LATEX_SOURCE, encoding="utf-8")

    print("Compiling Executive LaTeX Report via pdflatex...")
    try:
        for _ in range(2):  # Two passes for TikZ / layout resolution
            subprocess.run(
                [
                    "pdflatex", "-interaction=nonstopmode",
                    "-output-directory", str(build_dir), str(tex_path)
                ],
                check=True, stdout=subprocess.DEVNULL
            )
        print(f"Successfully compiled report to: {build_dir / 'methodology_report.pdf'}")
    except (subprocess.CalledProcessError, FileNotFoundError):
        print(
            "Notice: pdflatex (MiKTeX) not detected in system path. "
            "LaTeX source generated successfully in build/docs/."
        )

    # Automated cleanup of auxiliary files (.aux, .log, .out)
    for ext in [".aux", ".log", ".out"]:
        aux_file = build_dir / f"methodology_report{ext}"
        if aux_file.exists():
            aux_file.unlink()
    print("Auxiliary LaTeX build files cleaned successfully.")


if __name__ == "__main__":
    compile_pdf()
